import assert from 'node:assert/strict';
import test from 'node:test';
import {auditFigmaContractFacts} from '../../scripts/lib/figma-contract-facts.mjs';
import {createContractProofEnvironment} from '../../scripts/lib/contract-fact-proofs.mjs';
import {auditNativeRelationProofs} from '../../scripts/lib/native-relationship-coverage.mjs';
import {auditNativeContextProofs,applyNativeContextCoverage,validateNativeContextProofReferences} from '../../scripts/lib/native-context-coverage.mjs';
const SHA='a'.repeat(40),NONCE='b'.repeat(64),REQUEST='c'.repeat(64),SOURCE_REQUEST='d'.repeat(64),KEY='e'.repeat(40);
const OWNER='asset-owner',SOURCE='asset-source',clone=v=>structuredClone(v);
function native(id,type,name,size){return {node_id:id,node_type:type,name,visible:true,reference_dimensions:{width:size,height:size,unit:'px'},minimum_width_px:null,layout_align:'INHERIT',layout_grow:0,layout_positioning:'AUTO',clips_content:true,corner_radius:0,corner_radii:{top_left:0,top_right:0,bottom_right:0,bottom_left:0},fills:[{type:'solid',visible:true,opacity:1,color:'#FF0C56'}],strokes:[],opacity:1,rotation:0,variable_bindings:{},component_property_references:{}};}
function none(){return {mode:'NONE',horizontal_sizing:'FIXED',vertical_sizing:'FIXED',primary_axis_sizing:'AUTO',counter_axis_sizing:'FIXED',item_spacing:0,counter_axis_spacing:0,wrap:'NO_WRAP',primary_axis_alignment:'MIN',counter_axis_alignment:'MIN',padding:{top:0,right:0,bottom:0,left:0}};}
function fixture(){
 const asset={id:'badge',owner_layer_name:'Asset/Owner @4x',source_viewport:'desktop',source_mode_id:'rendered-node',display_mode_id:'direct-image',export_profile_id:'png-4x',alpha_mode_id:'transparent',clipping_policy_id:'preserve-artwork',export_boundary:{kind:'node',semantic_node_name:'Asset/Owner @4x'},pixel_dimensions:{width:288,height:288,unit:'px'},aspect_ratio:{width:72,height:72},crop:{mode:'none',position_source:'exact-node-after-overrides'},background:{own_visible_boundary_fill:'preserve',artificial_matte:'forbid'}};
 const root=native('72:1','COMPONENT','Asset/Owner @4x',72), artwork=native('72:2','INSTANCE','artwork',72), sourceRoot=native('44:1','COMPONENT','Partner source',44);
 root.layout=none();root.fills[0].visible=false;root.corner_radius=72;root.corner_radii={top_left:72,top_right:72,bottom_left:72,bottom_right:72};artwork.layout=none();artwork.main_component_id='44:1';artwork.instance_properties={};sourceRoot.layout=none();sourceRoot.remote_source={remote:true,component_key:KEY};
 const vector=native('44:2','VECTOR','Vector',38);delete vector.corner_radii;delete vector.clips_content;sourceRoot.children=[vector];artwork.children=[{...clone(vector),node_id:'I72:2;44:2'}];root.children=[artwork];
 const facts=[{id:'reference-size',value:{type:'dimensions',width:72,height:72,unit:'px'},provenance:{kind:'figma-literal',node_id:'72:1'}},...['horizontal-sizing','vertical-sizing','layout-wrap'].map((id,i)=>({id,value:{type:'keyword',value:['fixed','fixed','no_wrap'][i]},provenance:{kind:'figma-literal',node_id:'72:1'}}))];
 const htmlRoot={id:'root',semantic_role:'asset',render_mode:'direct-image',asset_contract_id:'badge',visibility:{mode:'always'},facts,children:[]};
 const owner={id:OWNER,identity:{library:'service',node_kind:'component',semantic_role:'asset',figma_name:'Asset/Owner @4x'},figma:{file_key:'native-file',node_id:'72:1'},properties:[],variants:[],asset_contracts:[asset],contracts:{mobile:{root:clone(htmlRoot)},desktop:{root:htmlRoot},figma_fact_links:[]},evidence_links:{foundation_values:[],source_dependencies:[{id:'source-link',source:{variant_node_id:'72:1',node_id:'72:2'},target:{component_id:SOURCE},asset_owner:{node_id:'72:1',asset_id:'badge'}}],native_relation_proofs:[{id:'owner-structure',kind:'element-structure',source:{component_id:OWNER,variant_node_id:'72:1',node_id:'72:1'},element_path:'/contracts/desktop/root'}],native_context_proofs:[]}};
 for(const viewport of ['desktop','mobile'])for(const [i,path,key,transform] of [[0,'/reference_dimensions/width','width','identity'],[0,'/reference_dimensions/height','height','identity'],[0,'/reference_dimensions/unit','unit','identity'],[1,'/layout/horizontal_sizing','value','lowercase'],[2,'/layout/vertical_sizing','value','lowercase'],[3,'/layout/wrap','value','lowercase']])owner.contracts.figma_fact_links.push({variant_node_id:'72:1',node_id:'72:1',source_path:path,contract_path:`/contracts/${viewport}/root/facts/${i}/value/${key}`,transform});
 const source={id:SOURCE,identity:{library:'shared',node_kind:'component',semantic_role:'asset',figma_name:'Partner source'},figma:{file_key:'native-file',node_id:'44:1',remote_source:{component_key:KEY}},properties:[],variants:[],asset_contracts:[],contracts:{mobile:{root:{id:'root',semantic_role:'asset',render_mode:'figma-source-only',visibility:{mode:'always'},facts:[],children:[]}},desktop:{root:{id:'root',semantic_role:'asset',render_mode:'figma-source-only',visibility:{mode:'always'},facts:[],children:[]}},figma_fact_links:[]},evidence_links:{foundation_values:[],source_dependencies:[],native_relation_proofs:[],native_context_proofs:[]}};
 const packet=(record,node,count,nonce)=>({capture_version:'1.3.0',file_key:'native-file',component_node_id:record.figma.node_id,owner_identity:{node_id:record.figma.node_id,node_type:'COMPONENT',name:record.identity.figma_name},capture_errors:[],component_properties:[],variants:[{variant_node_id:record.figma.node_id,axes:[],source_node:node}],capture_meta:{started_at:'2026-10-04T10:00:01.000Z',completed_at:'2026-10-04T10:00:02.000Z',tree_complete:true,node_count:count,request:{session_nonce:NONCE,request_nonce:nonce,canonical_git_sha:SHA}}});
 const ownerPacket=packet(owner,root,3,REQUEST),sourcePacket=packet(source,sourceRoot,2,SOURCE_REQUEST);
 const captures=[[owner,ownerPacket,REQUEST],[source,sourcePacket,SOURCE_REQUEST]].map(([r,p,nonce])=>({component_id:r.id,receipt_id:'receipt-'+r.id,tool:'use_figma',request_nonce:nonce,requested_at:'2026-10-04T10:00:01.000Z',received_at:'2026-10-04T10:00:03.000Z',packet:p}));
 const session={schema_version:'1.1.0',canonical_git_sha:SHA,session_nonce:NONCE,started_at:'2026-10-04T10:00:00.000Z',completed_at:'2026-10-04T10:00:04.000Z',component_ids:[OWNER,SOURCE],captures};
 return {owner,source,ownerPacket,sourcePacket,root,sourceRoot,artwork,session,model:{canonical_sha:SHA,records:[owner,source],source_documents:new Map(),manifest:{sources:[]}}};
}
function baseline(f){const env=createContractProofEnvironment(f.model,f.session);assert.deepEqual(env.issues,[]);env.dependencies(OWNER);const relations=auditNativeRelationProofs({record:f.owner,model:f.model,session:f.session});assert.equal(relations.ok,true,JSON.stringify(relations.issues));const raw=auditFigmaContractFacts({record:f.owner,live:f.ownerPacket});assert.equal(raw.issues.some(i=>['FIGMA_CONTRACT_MISMATCH','CONTRACT_FACT_UNMAPPED','FIGMA_SOURCE_PATH_MISSING'].includes(i.code)),false);}
function enroll(f){f.owner.evidence_links.native_context_proofs=[{id:'rendered-context',kind:'rendered-artwork-context',structure_proof_id:'owner-structure'}];f.source.evidence_links.native_context_proofs=[{id:'source-context',kind:'source-artwork-context',owner_component_id:OWNER,structure_proof_id:'owner-structure',dependency_link_id:'source-link'}];}
const audit=(f,record)=>auditNativeContextProofs({record,model:f.model,session:f.session});
test('artwork fixture authenticates actual shape and independent owner relation first',()=>baseline(fixture()));
test('rendered root guards reuse an owned verified node-export boundary',()=>{const f=fixture();baseline(f);enroll(f);assert.equal(audit(f,f.owner).ok,true);});
test('source root follows the exact rendered owner graph, not source44=display72=export288',()=>{const f=fixture();baseline(f);enroll(f);assert.equal(audit(f,f.source).ok,true);});
for(const [name,mutate] of [
 ['unknown owner',f=>f.source.evidence_links.native_context_proofs[0].owner_component_id='missing'],
 ['unknown structure',f=>f.source.evidence_links.native_context_proofs[0].structure_proof_id='missing'],
 ['unknown dependency',f=>f.source.evidence_links.native_context_proofs[0].dependency_link_id='missing'],
 ['wrong main',f=>f.artwork.main_component_id='44:3'],
 ['wrong remote key',f=>f.sourceRoot.remote_source.component_key='f'.repeat(40)],
 ['wrong asset owner',f=>f.owner.evidence_links.source_dependencies[0].asset_owner.node_id='72:2'],
 ['Fill export is not whole artwork',f=>f.owner.asset_contracts[0].source_mode_id='image-fill'],
 ['artificial matte',f=>f.owner.asset_contracts[0].background.artificial_matte='allow'],
 ['missing fresh source capture',f=>f.session.captures.pop()],
 ['unsupported source opacity',f=>f.sourceRoot.opacity=0.5],
 ['unknown metadata key',f=>f.source.evidence_links.native_context_proofs[0].fields=['/opacity']],
])test('artwork context rejects '+name,()=>{const f=fixture();baseline(f);enroll(f);mutate(f);assert.equal(audit(f,f.source).ok,false);});
test('role alone and caller success cannot remove source facts',()=>{const f=fixture(),facts=auditFigmaContractFacts({record:f.source,live:f.sourcePacket});assert.equal(applyNativeContextCoverage({facts,coverage:{ok:true,verified_sources:[]}}),facts);});
test('source artifact paint is preserved by current graph, not copied into HTML color',()=>{const f=fixture();baseline(f);enroll(f);f.sourceRoot.fills[0].color='#112233';assert.equal(audit(f,f.source).ok,true);});
test('unknown source field survives genuine coverage',()=>{const f=fixture();baseline(f);enroll(f);f.sourceRoot.future_native_field=true;const facts=auditFigmaContractFacts({record:f.source,live:f.sourcePacket}),coverage=audit(f,f.source),effective=applyNativeContextCoverage({facts,coverage});assert.equal(coverage.ok,true);assert.ok(effective.issues.some(i=>i.source_path==='/future_native_field'));assert.ok(!effective.issues.some(i=>i.source_path==='/reference_dimensions/width'));assert.ok(facts.issues.some(i=>i.source_path==='/reference_dimensions/width'));});
test('artwork metadata permits no caller values or arbitrary field masks',()=>{const f=fixture();enroll(f);f.source.evidence_links.native_context_proofs[0].expected_width=44;assert.ok(validateNativeContextProofReferences({records:f.model.records}).length);});
