import assert from 'node:assert/strict';
import test from 'node:test';
import {fixture} from './native-relationship-coverage.test.mjs';

const relation = await import('../../scripts/lib/native-relationship-coverage.mjs').catch(error => {
  const expected = new URL('../../scripts/lib/native-relationship-coverage.mjs', import.meta.url).href;
  if (error?.code === 'ERR_MODULE_NOT_FOUND' && error.url === expected) return {};
  throw error;
});
const copy = value => structuredClone(value);
function api() { assert.equal(typeof relation.auditNativeRelationProofs, 'function', 'native relation auditor must exist'); return relation; }
function nestedFixture() {
  const f = fixture(), child = copy(f.record);
  child.id = 'secondary-badge'; child.identity.figma_name = 'Badge'; child.figma = {file_key: 'native-file', node_id: '300:1'}; child.properties = [];
  child.variants = [{id: 'mobile-default', node_id: '301:1', axes: [{name: 'Viewport', value: 'Mobile'}, {name: 'State', value: 'Default'}]}, {id: 'desktop-default', node_id: '401:1', axes: [{name: 'Viewport', value: 'Desktop'}, {name: 'State', value: 'Default'}]}];
  child.evidence_links.native_relation_proofs = []; child.contracts.mobile.root = {id: 'root', facts: [{id: 'reference-size', value: {type: 'dimensions', width: 20, height: 20, unit: 'px'}, provenance: {kind: 'figma-literal', node_id: '301:1'}}], children: []}; child.contracts.desktop.root = {id: 'root', facts: [{id: 'reference-size', value: {type: 'dimensions', width: 20, height: 20, unit: 'px'}, provenance: {kind: 'figma-literal', node_id: '401:1'}}], children: []}; child.contracts.figma_fact_links = [{variant_node_id: '301:1', node_id: '301:1', source_path: '/reference_dimensions/width', contract_path: '/contracts/mobile/root/facts/0/value/width', transform: 'identity'}, {variant_node_id: '301:1', node_id: '301:1', source_path: '/reference_dimensions/height', contract_path: '/contracts/mobile/root/facts/0/value/height', transform: 'identity'}, {variant_node_id: '401:1', node_id: '401:1', source_path: '/reference_dimensions/width', contract_path: '/contracts/desktop/root/facts/0/value/width', transform: 'identity'}, {variant_node_id: '401:1', node_id: '401:1', source_path: '/reference_dimensions/height', contract_path: '/contracts/desktop/root/facts/0/value/height', transform: 'identity'}];
  const root = f.packet.variants[0].source_node, instance = root.children[0];
  instance.node_type = 'INSTANCE'; instance.name = 'badge'; instance.main_component_id = '301:1'; instance.instance_properties = {Viewport: {type: 'VARIANT', value: 'Mobile', boundVariables: {}}, State: {type: 'VARIANT', value: 'Default', boundVariables: {}}};
  const element = f.record.contracts.mobile.root.children[0]; element.semantic_role = 'badge'; element.render_mode = 'nested-component'; element.component_id = child.id; element.children = [];
  f.record.contracts.figma_fact_links.push({variant_node_id: '101:1', node_id: '101:2', source_path: '/instance_properties/Viewport/value', contract_path: '/contracts/mobile/root/children/0/facts/1/value/value', transform: 'lowercase'}, {variant_node_id: '101:1', node_id: '101:2', source_path: '/instance_properties/State/value', contract_path: '/contracts/mobile/root/children/0/facts/2/value/value', transform: 'lowercase'});
  element.facts.push({id: 'nested-viewport', value: {type: 'keyword', value: 'mobile'}, provenance: {kind: 'figma-literal', node_id: '101:2'}}, {id: 'nested-state', value: {type: 'keyword', value: 'default'}, provenance: {kind: 'figma-literal', node_id: '101:2'}});
  const childPacket = copy(f.packet); childPacket.component_node_id = '300:1'; childPacket.owner_identity = {node_id: '300:1', node_type: 'COMPONENT_SET', name: 'Badge'}; childPacket.component_properties = [{name: 'Viewport', type: 'VARIANT', default: 'Mobile', variant_options: ['Mobile', 'Desktop']}, {name: 'State', type: 'VARIANT', default: 'Default', variant_options: ['Default']}]; childPacket.capture_meta.node_count = 2; childPacket.variants = [{variant_node_id: '301:1', axes: child.variants[0].axes, source_node: {node_id: '301:1', node_type: 'COMPONENT', name: 'Viewport=Mobile, State=Default', visible: true, component_property_references: {}, reference_dimensions: {width: 20, height: 20, unit: 'px'}, children: []}}, {variant_node_id: '401:1', axes: child.variants[1].axes, source_node: {node_id: '401:1', node_type: 'COMPONENT', name: 'Viewport=Desktop, State=Default', visible: true, component_property_references: {}, reference_dimensions: {width: 20, height: 20, unit: 'px'}, children: []}}];
  f.model.records.push(child); f.session.component_ids.push(child.id); f.session.captures.push({component_id: child.id, receipt_id: 'receipt-badge', tool: 'use_figma', request_nonce: 'd'.repeat(64), requested_at: '2026-10-04T10:00:01.000Z', received_at: '2026-10-04T10:00:03.000Z', packet: childPacket}); childPacket.capture_meta.request.request_nonce = 'd'.repeat(64);
  return f;
}
function audit(f) { return api().auditNativeRelationProofs({record: f.record, model: f.model, session: f.session}); }
test('nested component verifies registered main component and exact instance axis mappings', () => { assert.equal(audit(nestedFixture()).ok, true); });
for (const [name, mutate] of [['foreign main component', f => {f.packet.variants[0].source_node.children[0].main_component_id = '999:1';}], ['wrong axis value', f => {f.packet.variants[0].source_node.children[0].instance_properties.Viewport.value = 'Desktop';}], ['wrong axis type', f => {f.packet.variants[0].source_node.children[0].instance_properties.State.type = 'BOOLEAN';}], ['bound-variable alias', f => {f.packet.variants[0].source_node.children[0].instance_properties.State.boundVariables = {alias: 'x'};}], ['missing axis mapping', f => {f.record.contracts.figma_fact_links.pop();}], ['flattened nested child', f => {f.record.contracts.mobile.root.children[0].render_mode = 'html-text';}]]) test(`nested component rejects ${name}`, () => { const f = nestedFixture(); assert.equal(audit(f).ok, true); mutate(f); assert.equal(audit(f).ok, false); });
