import assert from 'node:assert/strict';
import {readFileSync} from 'node:fs';
import test from 'node:test';
import vm from 'node:vm';
import {auditFigmaContractFacts} from '../../scripts/lib/figma-contract-facts.mjs';
import {createContractProofEnvironment} from '../../scripts/lib/contract-fact-proofs.mjs';

const sha='a'.repeat(40), nonce='b'.repeat(64), request='c'.repeat(64);
const source={component_id:'variable-fixture',variant_node_id:'101:1',node_id:'101:1'};
const variableId='VariableID:1:1', collectionId='VariableCollectionId:1:0';
const url=new URL('../../scripts/lib/native-variable-coverage.mjs',import.meta.url).href;
const subject=await import(url).catch(error=>error?.code==='ERR_MODULE_NOT_FOUND'&&error.url===url?{}:Promise.reject(error));
const api=()=>{for(const name of ['validateNativeVariableProofReferences','auditNativeVariableProofs','applyNativeVariableCoverage'])assert.equal(typeof subject[name],'function',`missing native variable coverage API: ${name}`);return subject;};
function native(id,viewport){return {node_id:id,node_type:'COMPONENT',name:`Viewport=${viewport}`,visible:true,component_property_references:{},reference_dimensions:{width:120,height:40,unit:'px'},layout:{mode:'VERTICAL',horizontal_sizing:'FIXED',vertical_sizing:'HUG',primary_axis_sizing:'AUTO',counter_axis_sizing:'FIXED',item_spacing:8,counter_axis_spacing:0,wrap:'NO_WRAP',primary_axis_alignment:'MIN',counter_axis_alignment:'MIN',padding:{top:0,right:0,bottom:0,left:0}},variable_bindings:{itemSpacing:{id:variableId}},children:[]};}
function fixture(){
  const root={id:'root',semantic_role:'card',render_mode:'presentation-table',visibility:{mode:'always'},component_property_references:{},facts:[{id:'reference-size',value:{type:'dimensions',width:120,height:40,unit:'px'},provenance:{kind:'figma-literal',node_id:'101:1'}},{id:'layout-gap',value:{type:'measure',value:8,unit:'px'},provenance:{kind:'figma-literal',node_id:'101:1'}}],children:[]};
  const proof={id:'gap-variable',kind:'variable-binding',source,contract_path:'/contracts/mobile/root/facts/1/value',binding_path:'/variable_bindings/itemSpacing/id',variable:{id:variableId,name:'Space/8',key:'space-8',collection_id:collectionId,collection_name:'Space',resolved_type:'FLOAT'}};
  const links=[['/reference_dimensions/width','/contracts/mobile/root/facts/0/value/width'],['/reference_dimensions/height','/contracts/mobile/root/facts/0/value/height'],['/layout/item_spacing','/contracts/mobile/root/facts/1/value/value']].map(([source_path,contract_path])=>({variant_node_id:'101:1',node_id:'101:1',source_path,contract_path,transform:'identity'}));
  const record={id:'variable-fixture',identity:{library:'service',node_kind:'component-set',semantic_role:'block',figma_name:'Variable fixture'},figma:{file_key:'native-file',node_id:'100:1'},properties:[],variants:[{id:'mobile',node_id:'101:1',axes:[{name:'Viewport',value:'Mobile'}]},{id:'desktop',node_id:'201:1',axes:[{name:'Viewport',value:'Desktop'}]}],asset_contracts:[],contracts:{mobile:{root},desktop:{root:{...structuredClone(root),facts:[]}},figma_fact_links:links},evidence_links:{foundation_values:[],source_dependencies:[],fact_proofs:[],normative_decisions:[],native_fact_proofs:[],native_relation_proofs:[],native_variable_proofs:[proof]}};
  const binding_evidence={variables:[{id:variableId,name:'Space/8',key:'space-8',remote:false,collection_id:collectionId,resolved_type:'FLOAT',values_by_mode:{'1:0':8}}],collections:[{id:collectionId,name:'Space',default_mode:'1:0',modes:[{id:'1:0',name:'Mobile'}]}],usages:[{node_id:'101:1',binding_path:'/variable_bindings/itemSpacing',variable_id:variableId,resolved_type:'FLOAT',resolved_value:8,mode_selections:[{collection_id:collectionId,mode_id:'1:0'}]}]};
  const packet={capture_version:'1.3.0',file_key:'native-file',component_node_id:'100:1',capture_errors:[],owner_identity:{node_id:'100:1',node_type:'COMPONENT_SET',name:'Variable fixture'},component_properties:[],capture_meta:{started_at:'2026-10-04T10:00:01.000Z',completed_at:'2026-10-04T10:00:02.000Z',tree_complete:true,node_count:2,request:{session_nonce:nonce,request_nonce:request,canonical_git_sha:sha}},variants:[{variant_node_id:'101:1',axes:[{name:'Viewport',value:'Mobile'}],source_node:native('101:1','Mobile')},{variant_node_id:'201:1',axes:[{name:'Viewport',value:'Desktop'}],source_node:native('201:1','Desktop')}],binding_evidence};
  const session={schema_version:'1.1.0',canonical_git_sha:sha,session_nonce:nonce,started_at:'2026-10-04T10:00:00.000Z',completed_at:'2026-10-04T10:00:04.000Z',component_ids:[record.id],captures:[{component_id:record.id,receipt_id:'receipt',tool:'use_figma',request_nonce:request,requested_at:'2026-10-04T10:00:01.000Z',received_at:'2026-10-04T10:00:03.000Z',packet}]};return {record,packet,session,model:{canonical_sha:sha,records:[record],source_documents:new Map(),manifest:{sources:[]}}};}
function baseline(x){const facts=auditFigmaContractFacts({record:x.record,live:x.packet});assert.equal(facts.issues.some(i=>['FIGMA_CONTRACT_MISMATCH','CONTRACT_FACT_UNMAPPED'].includes(i.code)),false,'raw baseline maps literal 8 before mutation');const env=createContractProofEnvironment(x.model,x.session);assert.equal(env.issues.length,0);env.tree(x.record.id);env.selected(source);assert.equal(env.issues.length,0);return facts;}
function rejects(mutator){const x=fixture();baseline(x);mutator(x);assert.equal(api().auditNativeVariableProofs({record:x.record,model:x.model,session:x.session}).ok,false);}

test('exact variable binding closes the literal layout-gap',()=>{const x=fixture();baseline(x);assert.equal(api().auditNativeVariableProofs({record:x.record,model:x.model,session:x.session}).ok,true);});
test('wrong resolved value cannot close a variable binding',()=>rejects(x=>x.packet.binding_evidence.usages[0].resolved_value=7));
test('missing or duplicate usage is refused',()=>{rejects(x=>x.packet.binding_evidence.usages=[]);rejects(x=>x.packet.binding_evidence.usages.push(structuredClone(x.packet.binding_evidence.usages[0])));});
test('unknown proof field remains closed',()=>{const x=fixture();baseline(x);x.record.evidence_links.native_variable_proofs[0].unknown=true;assert.ok(api().validateNativeVariableProofReferences({records:[x.record]}).length>0);});
test('copied, foreign, and mutated coverage cannot filter facts',()=>{const x=fixture(),facts=baseline(x),coverage=api().auditNativeVariableProofs({record:x.record,model:x.model,session:x.session});for(const bad of [structuredClone(coverage),{...coverage,session_nonce:'foreign'},{...coverage,results:[]}])assert.equal(api().applyNativeVariableCoverage({facts,coverage:bad,contractProofs:{},nativeFactProofs:{},nativeRelationProofs:{}}),facts);});
test('same value with a different variable identity is refused',()=>rejects(x=>x.packet.binding_evidence.usages[0].variable_id='VariableID:other'));
test('same value with a wrong variable type is refused',()=>rejects(x=>x.packet.binding_evidence.usages[0].resolved_type='COLOR'));
test('wrong consumer mode is refused',()=>rejects(x=>x.packet.binding_evidence.usages[0].mode_selections[0].mode_id='1:99'));
test('cross-packet raw field change cannot close coverage',()=>rejects(x=>x.packet.variants[0].source_node.layout.item_spacing=9));
test('serialized COMPONENT root preserves one binding usage and restores capture policy',async()=>{
  const calls={variable:0,collection:0}; const variable={id:variableId,name:'Space/8',key:'space-8',remote:false,resolvedType:'FLOAT',variableCollectionId:collectionId,valuesByMode:{'1:0':8},resolveForConsumer:async()=>({value:8,resolvedType:'FLOAT'})}; const collection={id:collectionId,name:'Space',defaultModeId:'1:0',modes:[{modeId:'1:0',name:'Mobile'}]};
  const figma={fileKey:'native-file',mixed:Symbol(),skipInvisibleInstanceChildren:false,getNodeByIdAsync:async()=>({id:'101:1',type:'COMPONENT',name:'Viewport=Mobile',visible:true,width:120,height:40,children:[],itemSpacing:8,layoutMode:'VERTICAL',layoutSizingHorizontal:'FIXED',layoutSizingVertical:'HUG',primaryAxisSizingMode:'AUTO',counterAxisSizingMode:'FIXED',counterAxisSpacing:0,layoutWrap:'NO_WRAP',primaryAxisAlignItems:'MIN',counterAxisAlignItems:'MIN',paddingTop:0,paddingRight:0,paddingBottom:0,paddingLeft:0,componentPropertyDefinitions:{},boundVariables:{itemSpacing:{type:'VARIABLE_ALIAS',id:variableId}},resolvedVariableModes:{[collectionId]:'1:0'}}),getStyleByIdAsync:async()=>null,variables:{getVariableByIdAsync:async()=>{calls.variable++;return variable},getVariableCollectionByIdAsync:async()=>{calls.collection++;return collection},getLocalVariablesAsync:async()=>[variable],getLocalVariableCollectionsAsync:async()=>[collection]}};
  const context={figma,console};vm.runInNewContext(`${readFileSync(new URL('../../scripts/figma/capture-contract-source.js',import.meta.url),'utf8')};globalThis.capture=captureFigmaContractFacts`,context);const packet=await context.capture('101:1',{session_nonce:nonce,request_nonce:request,canonical_git_sha:sha});assert.ok(packet.binding_evidence,'binding_evidence required');assert.equal(packet.variants.length,1);assert.equal(packet.binding_evidence.usages.length,1);assert.equal(packet.binding_evidence.usages[0].resolved_value,8);assert.equal(packet.binding_evidence.collections[0].default_mode,'1:0');assert.ok(calls.variable>0&&calls.collection>0);assert.equal(figma.skipInvisibleInstanceChildren,false);
});
test('valid alias chain resolves 8 while an alias cycle is refused',()=>{const x=fixture();baseline(x);x.packet.binding_evidence.variables[0].values_by_mode['1:0']={type:'VARIABLE_ALIAS',id:'VariableID:1:2'};x.packet.binding_evidence.variables.push({id:'VariableID:1:2',name:'Space terminal',key:'space-terminal',remote:false,collection_id:collectionId,resolved_type:'FLOAT',values_by_mode:{'1:0':8}});assert.equal(api().auditNativeVariableProofs({record:x.record,model:x.model,session:x.session}).ok,true);x.packet.binding_evidence.variables[1].values_by_mode['1:0']={type:'VARIABLE_ALIAS',id:variableId};assert.equal(api().auditNativeVariableProofs({record:x.record,model:x.model,session:x.session}).ok,false);});
test('authenticated variable coverage removes only the verified binding while preserving future fields',()=>{const x=fixture();x.packet.variants[0].source_node.future_field='keep';const raw=baseline(x),coverage=api().auditNativeVariableProofs({record:x.record,model:x.model,session:x.session});const effective=api().applyNativeVariableCoverage({facts:raw,coverage,contractProofs:{},nativeFactProofs:{},nativeRelationProofs:{}});assert.notEqual(effective,raw);assert.equal(effective.report.variants[0].source_node.future_field,'keep');assert.ok(!('itemSpacing' in effective.report.variants[0].source_node.variable_bindings));assert.equal(effective.report.variants[1].source_node.variable_bindings.itemSpacing.id,variableId);coverage.verified_sources[0].node_id='mutated';assert.equal(api().applyNativeVariableCoverage({facts:raw,coverage,contractProofs:{},nativeFactProofs:{},nativeRelationProofs:{}}),raw);});
