import assert from "node:assert/strict";
import test from "node:test";
import * as m from "../../scripts/lib/figma-component-evidence.mjs";
import { auditFigmaContractFacts } from "../../scripts/lib/figma-contract-facts.mjs";
const SHA="a".repeat(40), n=i=>i.toString(16).padStart(64,"0"), SN=n(1), api=m.auditNestedArtworkEvidence;
test("nested artwork public auditor is exported",()=>assert.equal(typeof api,"function"));
const axes=v=>v?[{name:"Viewport",value:v}]:[];
const node=(id,type,children=[],name=id)=>({node_id:id,node_type:type,name,visible:true,opacity:1,reference_dimensions:{width:24,height:24,unit:"px"},children});
function packet(id,root,request,variantAxes=axes("Desktop")){const count=x=>1+(x.children??[]).reduce((s,c)=>s+count(c),0);return{capture_version:"1.2.0",file_key:"synthetic",component_node_id:id,component_properties:[],capture_errors:[],capture_meta:{started_at:"2040-01-01T00:00:00.000Z",completed_at:"2040-01-01T00:00:01.000Z",request:{session_nonce:SN,request_nonce:request,canonical_git_sha:SHA},tree_complete:true,node_count:count(root)},variants:[{variant_node_id:id,axes:variantAxes,source_node:root}]};}
function fixture({frame=false,hidden=false,multilevel=false}={}){
 const glyph=node("500:1","COMPONENT",[],"glyph @4x"), artwork=frame?node("I300:1;I400:1;400:9","FRAME",[node("I300:1;I400:1;400:10","VECTOR",[],"artwork vector")],"artwork @4x"):{...node("I300:1;I400:1;500:1","INSTANCE",[],"artwork @4x"),main_component_id:"500:1"};artwork.visible=!hidden;
 const itemRoot=node("400:1","COMPONENT",[artwork],"Item/Desktop"), itemMobile=node("400:2","COMPONENT",[],"Item/Mobile"), itemInstance={...node(multilevel?"I300:1;350:1;400:1":"I300:1;400:1","INSTANCE",[artwork],"Item"),main_component_id:"400:1"}, parentRoot=node("300:1","COMPONENT",[multilevel?node("I300:1;350:1","FRAME",[itemInstance],"wrapper"):itemInstance],"Parent/Desktop");
 const parent={id:"parent",identity:{semantic_role:"block",node_kind:"component-set"},figma:{file_key:"synthetic",node_id:"300:1"},variants:[{node_id:"300:1",axes:axes("Desktop")},{node_id:"300:2",axes:axes("Mobile")}],asset_contracts:[],evidence_links:{foundation_values:[],source_dependencies:[]},contracts:{desktop:{root:{render_mode:"html",children:[{component_id:"item",facts:[{id:"reference-size",value:{type:"dimensions",width:24,height:24,unit:"px"},provenance:{kind:"figma-literal",node_id:artwork.node_id}}]}]}},mobile:{root:{render_mode:"html",children:[]}},figma_fact_links:[{variant_node_id:"300:1",node_id:artwork.node_id,source_path:"/reference_dimensions/width",contract_path:"/contracts/desktop/root/children/0/facts/0/value/width",transform:"identity"},{variant_node_id:"300:1",node_id:artwork.node_id,source_path:"/reference_dimensions/height",contract_path:"/contracts/desktop/root/children/0/facts/0/value/height",transform:"identity"}]}};
 const item={id:"item",identity:{semantic_role:"item",node_kind:"component-set"},figma:{file_key:"synthetic",node_id:"400:1"},variants:[{node_id:"400:1",axes:axes("Desktop")},{node_id:"400:2",axes:axes("Mobile")}],asset_contracts:[{id:"item-artwork",owner_layer_name:"artwork @4x",export_boundary:{kind:"node",semantic_node_name:"artwork @4x"}}],evidence_links:{foundation_values:[],source_dependencies:frame?[]:[{id:"glyph-main",source:{variant_node_id:"400:1",node_id:"I300:1;I400:1;500:1",field_path:"/main_component_id"},asset_owner:{component_id:"item",node_id:artwork.node_id,asset_id:"item-artwork"},target:{component_id:"glyph",variant_id:"500:1"}}]},contracts:{desktop:{root:{render_mode:"html",children:[]}},mobile:{root:{render_mode:"html",children:[]}},figma_fact_links:[]}};
 const child={id:"glyph",identity:{semantic_role:"asset",node_kind:"component"},figma:{file_key:"synthetic",node_id:"500:1"},variants:[],asset_contracts:[{id:"glyph-export",owner_layer_name:"glyph @4x",export_boundary:{kind:"node",semantic_node_name:"glyph @4x"}}],evidence_links:{foundation_values:[],source_dependencies:[]},contracts:{desktop:{root:{render_mode:"figma-source-only",children:[]}},mobile:{root:{render_mode:"figma-source-only",children:[]}},figma_fact_links:[]}};
 const pp=packet("300:1",parentRoot,n(2)),ip=packet("400:1",itemRoot,n(3)),gp=packet("500:1",glyph,n(4),[]), captures=[["parent",pp,n(2)],["item",ip,n(3)],["glyph",gp,n(4)]].map(([component_id,packet,request_nonce],i)=>({component_id,receipt_id:`${component_id}-receipt`,tool:"use_figma",request_nonce,requested_at:`2026-10-02T00:00:0${i}.000Z`,received_at:`2026-10-02T00:00:0${i+1}.000Z`,packet_path:`${component_id}.json`,packet_sha256:String(i+1).repeat(64),packet}));
 return{parent,item,child,artwork,pp,ip,gp,model:{canonical_sha:SHA,records:[parent,item,child],manifest:{sources:[]},source_documents:new Map(),targets:new Map()},session:{schema_version:"1.1.0",canonical_git_sha:SHA,session_nonce:SN,started_at:"2026-10-02T00:00:00.000Z",completed_at:"2026-10-02T00:00:05.000Z",component_ids:["parent","item","glyph"],captures}};
}
const run=f=>api({recordId:"parent",model:f.model,session:f.session}), has=(r,c)=>r.issues.some(x=>x.code===c);
function rejects(name,expected,change){test(name,{skip:typeof api!=="function"},()=>{const f=fixture();change(f);const r=run(f);assert.equal(r.ok,false);assert.ok(has(r,expected),JSON.stringify(r));});}
test("FRAME+VECTOR child artwork is a valid zero-INSTANCE boundary",{skip:typeof api!=="function"},()=>{const r=run(fixture({frame:true}));assert.equal(r.ok,true);assert.deepEqual(r.dependencies,[]);});
test("INSTANCE artwork qualifies Item ownership and preserves child identity",{skip:typeof api!=="function"},()=>{const r=run(fixture());assert.equal(r.ok,true);assert.equal(r.dependencies[0].asset_owner.component_id,"item");});
test("hidden and multilevel artwork remain positive",{skip:typeof api!=="function"},()=>{assert.equal(run(fixture({hidden:true})).ok,true);assert.equal(run(fixture({multilevel:true})).ok,true);});
test("combined keeps scalar facts exact and exposes nested result",{skip:typeof api!=="function"},()=>{const f=fixture(),s=auditFigmaContractFacts({record:f.parent,live:f.pp}),r=m.auditFigmaComponentEvidence({record:f.parent,live:f.pp,model:f.model,session:f.session});assert.deepEqual(r.facts,s);assert.ok(r.nested_artwork);});
rejects("wrong selector is typed","EVIDENCE_NESTED_SELECTOR_UNVERIFIED",f=>f.item.asset_contracts[0].export_boundary.semantic_node_name="wrong");
rejects("missing or duplicate owned geometry is typed","EVIDENCE_NESTED_GEOMETRY_UNVERIFIED",f=>f.parent.contracts.figma_fact_links.pop());
rejects("wrong placement main is typed","EVIDENCE_NESTED_PLACEMENT_UNVERIFIED",f=>f.artwork.main_component_id="500:9");
rejects("stale source is typed","EVIDENCE_REQUEST_IDENTITY_MISMATCH",f=>f.ip.capture_meta.request.request_nonce=n(9));
rejects("missing child packet is typed","EVIDENCE_CAPTURE_MISSING",f=>f.session.captures.pop());
rejects("unknown glyph remains typed without a source record","EVIDENCE_NESTED_TARGET_UNKNOWN",f=>f.item.evidence_links.source_dependencies[0].target.component_id="unknown-glyph");
rejects("stripped alias and wrong ancestry are typed","EVIDENCE_NESTED_ANCESTRY_UNVERIFIED",f=>f.artwork.node_id="500:1");
rejects("overridden actual glyph main is compared","EVIDENCE_NESTED_PLACEMENT_UNVERIFIED",f=>f.artwork.main_component_id="500:2");
test("ordinary HTML has no added artwork scope and inputs are immutable",{skip:typeof api!=="function"},()=>{const f=fixture({frame:true}),before=structuredClone({model:f.model,session:f.session});f.item.asset_contracts=[];const r=run(f);assert.equal(r.ok,true);assert.deepEqual(r.dependencies,[]);assert.deepEqual({model:f.model,session:f.session},before);});
